## SPDX-FileCopyrightText: Winni Neessen <wn@neessen.dev>
##
## SPDX-License-Identifier: MIT

[run]
go = "1.23"
tests = true
exclude-dirs = ["examples"]

[linters]
enable = ["stylecheck", "whitespace", "containedctx", "contextcheck", "decorder",
    "errname", "errorlint", "gofmt", "gofumpt", "gosec"]

[issues]

## An overflow is impossible here
[[issues.exclude-rules]]
linters = ["gosec"]
path = "tls.go"
text = "G402:"
